<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-02-27T17:37:09+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Probimor',
        ],
    ],
];
